title: "StoreClass"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2425S1-CS2103T-W10-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
