title: "Clientele+"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2425S1-CS2103T-F14A-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
